#!/usr/bin/env node
'use strict';

// evalagentvalues.js — score an agent's value() against a file of position
// evaluations (as generated by gen-agent-evals.js).
//
// Input lines are the concise gen-agent-evals format:
//   <size> <move1,move2,...> <winRatio> pass
// where winRatio = P(side-to-move wins) from the generating oracle.  '#' lines
// (generation parameters / load banners) are skipped.
//
// For each position we replay the moves, ask the agent for valueB(game) →
// P(BLACK wins), convert to P(side-to-move wins), and compare to the file's
// winRatio.  Errors are reported as MSE / RMS / MAE in win-probability [0,1]
// units — the SAME units as train_ppat's teMSE, so the score is directly
// comparable to a training run's test MSE.  Mean signed bias is also reported.
//
// Scoring an agent against a file it generated itself is a correctness check:
// a deterministic value() should score ~0 RMS.
//
// Usage:
//   node evalagentvalues.js --agent <name> --file <path> [--limit <n>]
//                           [--oversample <n>] [--seed <n>] [--show-phases <P>] [--verbose]
//
//   --agent        ai agent name under ai/ (must export valueB)   (required)
//   --file         evals file from gen-agent-evals.js             (required)
//   --limit        score only the first n positions               (default: all)
//   --oversample   score each position this many times            (default: 1)
//   --seed         starting agent rng seed                        (default: 1)
//   --show-phases P  print a P-row table of phase-band → RMS/bias, binning by
//                  game phase (board fullness, in [0,1])
//   --verbose      print a per-position pred/target/err table

const fs   = require('fs');
const path = require('path');
const { performance } = require('perf_hooks');
const { Game2, BLACK, parseMove } = require('./game2.js');
const { makeRng } = require('./xorshift.js');
const Util = require('./util.js');

let agentSeed = 1;   // per-invocation agent rng (some value()s are stochastic)

// Parse the concise gen-agent-evals format into { size, moves[], target }.
function loadPositions(filePath) {
  const out = [];
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const l = line.trim();
    if (!l || l.startsWith('#')) continue;   // '#' = generation params / banners
    const parts = l.split(/\s+/);
    if (parts.length < 3) continue;
    out.push({
      size:   parseInt(parts[0], 10),
      moves:  parts[1] ? parts[1].split(',') : [],
      target: parseFloat(parts[2]),           // P(side-to-move wins)
    });
  }
  return out;
}

// Sentinel: position replayed fine but its phase is outside [minPhase, maxPhase].
const FILTERED = { filtered: true };

// Replay to the position and score the agent's value.  Returns
// { pred, target, err, phase }; null if the move sequence doesn't replay legally
// (corrupt/unreachable data — surfaced, not silently scored); or FILTERED if the
// board phase (fullness) is outside [minPhase, maxPhase] (checked before the
// expensive valueB call, so filtered positions cost nothing).
function evalPosition(valueB, pos, minPhase = 0, maxPhase = 1) {
  const { size, moves, target } = pos;
  const game = new Game2(size);
  for (const m of moves) {
    if (!game.play(parseMove(m, size))) return null;
  }
  const phase = game.phase();
  if (phase < minPhase || phase > maxPhase) return FILTERED;
  const pBlack = valueB(game, { rng: makeRng(agentSeed++) });    // P(BLACK wins)
  const pred   = game.current === BLACK ? pBlack : 1 - pBlack;   // P(side-to-move wins)
  return { pred, target, err: pred - target, phase };
}

if (require.main === module) {
  const opts = Util.parseArgs(process.argv.slice(2),
    ['help', 'verbose'],
    ['agent', 'file', 'limit', 'oversample', 'seed', 'show-phases', 'min-phase', 'max-phase']);

  if (opts.help || !opts.file || !opts.agent) {
    console.log('Usage: node evalagentvalues.js --agent <name> --file <path> [--limit <n>] [--min-phase <p>] [--max-phase <p>] [--oversample <n>] [--seed <n>] [--show-phases <P>] [--verbose]');
    process.exit(opts.help ? 0 : 1);
  }

  const agentName  = opts.agent;
  const limit      = opts.limit !== undefined ? parseInt(opts.limit, 10) : Infinity;
  const oversample = parseInt(opts.oversample || '1', 10);
  const showPhases = opts['show-phases'] !== undefined ? parseInt(opts['show-phases'], 10) : null;
  const minPhase   = opts['min-phase'] !== undefined ? parseFloat(opts['min-phase']) : 0;
  const maxPhase   = opts['max-phase'] !== undefined ? parseFloat(opts['max-phase']) : 1;
  const verbose    = !!opts.verbose;

  if (isNaN(limit) || limit < 1)           { console.error('--limit must be a positive integer'); process.exit(1); }
  if (isNaN(oversample) || oversample < 1) { console.error('--oversample must be a positive integer'); process.exit(1); }
  if (showPhases !== null && (isNaN(showPhases) || showPhases < 1)) { console.error('--show-phases must be a positive integer'); process.exit(1); }
  if (isNaN(minPhase) || isNaN(maxPhase) || minPhase > maxPhase) { console.error('--min-phase/--max-phase must be numbers with min <= max'); process.exit(1); }
  if (opts.seed !== undefined) { agentSeed = parseInt(opts.seed, 10); if (isNaN(agentSeed)) { console.error('--seed must be an integer'); process.exit(1); } }

  // Construct factory agents eagerly via create() so their load banner prints
  // now, above the results table, instead of lazily on the first value() call.
  const agentMod  = require(path.join(__dirname, 'ai', agentName + '.js'));
  const agentInst = typeof agentMod.create === 'function' ? agentMod.create() : agentMod;
  const valueB    = agentInst.valueB;
  if (typeof valueB !== 'function') {
    console.error(`Agent '${agentName}' does not export a valueB() method`);
    process.exit(1);
  }

  const pool      = loadPositions(opts.file);
  const positions = pool.slice(0, limit);
  if (positions.length === 0) { console.error(`no positions in ${opts.file}`); process.exit(1); }

  const phaseWindow = (minPhase > 0 || maxPhase < 1) ? `  phase=[${minPhase},${maxPhase}]` : '';
  console.log(`agent=${agentName}  file=${opts.file}  positions=${positions.length}/${pool.length}${phaseWindow}  oversample=${oversample}`);
  console.log();
  console.log(['pos'.padStart(6), 'elapsed'.padStart(7), 'valMs'.padStart(6), 'rms'.padStart(6)].join('  '));

  // Phase bands: partition phase ∈ [0,1] (board fullness) into P equal-width bands.
  let bandSq = null, bandErr = null, bandN = null;
  if (showPhases !== null) {
    bandSq  = new Float64Array(showPhases);
    bandErr = new Float64Array(showPhases);
    bandN   = new Int32Array(showPhases);
  }
  const bandOf = (phase) => Math.min(showPhases - 1, Math.max(0, Math.floor(phase * showPhases)));

  const startTime = performance.now();
  let printPeriodMs = 1000, lastPrintTime = startTime;
  let sqSum = 0, absSum = 0, errSum = 0, n = 0, skipped = 0, filtered = 0;

  function printStats() {
    const elapsedMs = performance.now() - startTime;
    console.log([
      Util.fmt4i(n).padStart(6),
      Util.fmtMs(elapsedMs).padStart(7),
      Util.fmtMs(elapsedMs / Math.max(1, n)).padStart(6),
      Util.fmtRatio4(Math.sqrt(sqSum / Math.max(1, n))).padStart(6),
    ].join('  '));
  }

  if (verbose) {
    console.log(`\n${'idx'.padStart(6)}  ${'hist'.padStart(4)}  ${'phase'.padStart(5)}  ${'pred'.padStart(6)}  ${'target'.padStart(6)}  ${'err'.padStart(7)}`);
  }

  for (let j = 0; j < oversample; j++) {
    for (let i = 0; i < positions.length; i++) {
      const r = evalPosition(valueB, positions[i], minPhase, maxPhase);
      if (r === null) {
        skipped++;
        if (skipped <= 5) console.error(`WARNING: position idx ${i} did not replay legally; skipping`);
        continue;
      }
      if (r === FILTERED) { filtered++; continue; }
      sqSum += r.err * r.err; absSum += Math.abs(r.err); errSum += r.err; n++;
      if (showPhases !== null) { const b = bandOf(r.phase); bandSq[b] += r.err * r.err; bandErr[b] += r.err; bandN[b]++; }
      if (verbose) console.log(
        `${String(i).padStart(6)}  ${String(positions[i].moves.length).padStart(4)}  ` +
        `${r.phase.toFixed(3).padStart(5)}  ${r.pred.toFixed(4).padStart(6)}  ` +
        `${r.target.toFixed(4).padStart(6)}  ${(r.err >= 0 ? '+' : '') + r.err.toFixed(4)}`.padStart(7));

      const now = performance.now();
      if (now - lastPrintTime >= printPeriodMs) {
        lastPrintTime = now; printPeriodMs = Math.round(printPeriodMs * 1.5); printStats();
      }
    }
  }

  printStats();
  if (filtered) console.log(`\nfiltered ${filtered} position(s) outside phase [${minPhase},${maxPhase}]`);
  if (skipped) console.log(`\nskipped ${skipped} position(s) that did not replay legally`);

  if (n === 0) { console.error(`\nno positions scored (all filtered/skipped)`); process.exit(1); }
  const mse = sqSum / n, rms = Math.sqrt(mse), mae = absSum / n, bias = errSum / n;
  console.log(`\nscored ${n} evals   MSE ${mse.toFixed(5)}   RMS ${rms.toFixed(5)}   MAE ${mae.toFixed(5)}   bias ${(bias >= 0 ? '+' : '') + bias.toFixed(5)}   (win-prob [0,1] units)`);

  if (showPhases !== null) {
    console.log(`\nPhase bands:`);
    console.log(['phase'.padStart(9), 'n'.padStart(6), 'rms'.padStart(6), 'bias'.padStart(7)].join('  '));
    for (let b = 0; b < showPhases; b++) {
      const cnt = bandN[b];
      const lo = (b / showPhases).toFixed(2), hi = ((b + 1) / showPhases).toFixed(2);
      const rmsB  = cnt > 0 ? Util.fmtRatio4(Math.sqrt(bandSq[b] / cnt)) : '-';
      const biasB = cnt > 0 ? ((bandErr[b] / cnt >= 0 ? '+' : '') + (bandErr[b] / cnt).toFixed(3)) : '-';
      console.log([`${lo}-${hi}`.padStart(9), Util.fmt4i(cnt).padStart(6), rmsB.padStart(6), biasB.padStart(7)].join('  '));
    }
  }
}

module.exports = { loadPositions, evalPosition };
