'use strict';

// npats-lib.js — search-distilled move policy: a linear softmax over the
// shared pattern/tactical features, with its own weight storage, scoring,
// and persistence (npat-lib supplies only feature extraction).
//
// Weights are keyed by raw canonical feature ids (no interning layer):
//   shape keys   — canonKey ints from the 3×3c / P12 windows
//   tactical[k]  — TACT_RAW_BASE + k for k ∈ 0..N_TACT_SLOTS-1
// and stored in an int→float open-addressing map.  Raw key 0 is a real
// feature (the all-empty 3×3 window), so keys are biased by +1 inside the
// map (int-map reserves key 0); the bias never leaves this module.
//
// Persistence is a dual-environment JS module holding the entries as base64
// typed arrays — `count` Int32 raw keys followed by `count` Float32 weights:
//
//   const npatsModel = (() => { ... decode base64 ... })();
//   // → { version, count, cfg, keys: Int32Array, vals: Float32Array }
//
// A `count` of 0 is a valid model: every logit is 0, the softmax is uniform —
// that is the generation-0 bootstrap, no special casing.
//
// BROWSER-COMPATIBLE: in the browser, set window.npatsModel before
// requiring; loadModel reads it instead of a file.

(function () {

const Util = (typeof require === 'function') ? require('./util.js') : window.Util;
const NPat = Util.load('./npat-lib.js', 'NPatterns');
const { makeIntFloatMap } = Util.load('./int-map.js', 'IntMap');

const VERSION = 1;

// Raw keys are non-negative and the map reserves 0, so store at raw+1.
const KEY_BIAS = 1;

// ── Weights ───────────────────────────────────────────────────────────────────

// A fresh empty model with the canonical feature configuration.
function freshModel() {
  return {
    weights: makeWeights(),
    cfg: { useTactical: true, use33c: true, useP12: true, tactStoneLimit: NPat.TACT_STONE_LIMIT },
  };
}

// A mutable weight store keyed by raw canonical feature id.  Map-like:
// get() returns undefined for absent keys (use `?? 0`).
function makeWeights(minCap) {
  const map = makeIntFloatMap(minCap);
  return {
    get(rawKey)    { return map.get(rawKey + KEY_BIAS); },
    set(rawKey, v) { map.set(rawKey + KEY_BIAS, v); },
    forEach(fn)    { map.forEach((k, v) => fn(k - KEY_BIAS, v)); },
    get size()     { return map.size; },
  };
}

// ── Persistence ───────────────────────────────────────────────────────────────

// Render a model as dual-environment JS module source.  `comment` (optional)
// is a one-line provenance note for the file header.
function packModel(weights, cfg, comment) {
  const count = weights.size;
  const keys = new Int32Array(count);
  const vals = new Float32Array(count);
  let i = 0;
  weights.forEach((k, v) => { keys[i] = k; vals[i] = v; i++; });
  const bytes = Buffer.concat([
    Buffer.from(keys.buffer, 0, count * 4),
    Buffer.from(vals.buffer, 0, count * 4),
  ]);
  return [
    "'use strict';",
    '// Auto-generated by npats-lib.js — do not edit by hand.',
    ...(comment ? ['// ' + comment] : []),
    'const npatsModel = (() => {',
    `  const count = ${count};`,
    `  const cfg = ${JSON.stringify(cfg)};`,
    `  const b64 = '${bytes.toString('base64')}';`,
    "  const bytes = typeof Buffer !== 'undefined'",
    "    ? Buffer.from(b64, 'base64')",
    '    : Uint8Array.from(atob(b64), c => c.charCodeAt(0));',
    '  const buf = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + count * 8);',
    `  return { version: ${VERSION}, count, cfg,`,
    '           keys: new Int32Array(buf, 0, count),',
    '           vals: new Float32Array(buf, count * 4, count) };',
    '})();',
    "if (typeof module !== 'undefined') module.exports = npatsModel;",
    'else window.npatsModel = npatsModel;',
    '',
  ].join('\n');
}

// Write a model file (Node only).
function saveModel(filePath, weights, cfg, comment) {
  require('fs').writeFileSync(filePath, packModel(weights, cfg, comment));
}

// Build runtime weights from a raw model object (a required model file or
// window.npatsModel).  Validates version and the tactical stone limit.
// `name` prefixes error messages.  Returns { weights, cfg }.
function prepareWeights(raw, name = 'npats') {
  if (raw.version !== VERSION) {
    throw new Error(`${name}: npats model version ${raw.version} — runtime expects ${VERSION}`);
  }
  if (raw.cfg.tactStoneLimit !== undefined && raw.cfg.tactStoneLimit !== NPat.TACT_STONE_LIMIT) {
    throw new Error(
      `${name}: TACT_STONE_LIMIT mismatch — model was trained at ${raw.cfg.tactStoneLimit}, ` +
      `runtime is ${NPat.TACT_STONE_LIMIT}. Set NPAT_STONE_LIMIT=${raw.cfg.tactStoneLimit} before launching.`
    );
  }
  const weights = makeWeights(Math.max(64, 2 * raw.count));
  for (let i = 0; i < raw.count; i++) weights.set(raw.keys[i], raw.vals[i]);
  return { weights, cfg: raw.cfg };
}

// Resolve the policy model source and build runtime weights from it.
//   name — message prefix (typically the agent name)   (default 'policy')
//   path — model file path, Node only                  (default ./npats-data.js)
// In the browser the source is always window.npatsModel.
// Returns { weights, cfg, modelName }.
function loadModel({ name = 'npats', path: pathOverride } = {}) {
  let raw, modelName;
  if (typeof window !== 'undefined') {
    if (!window.npatsModel) {
      throw new Error(`${name}: window.npatsModel is not set — load the npats weights script first`);
    }
    raw = window.npatsModel;
    modelName = 'window.npatsModel';
  } else {
    const path = require('path');
    const file = pathOverride || path.join(__dirname, 'npats-data.js');
    raw = require(path.resolve(file));
    modelName = path.basename(file);
  }
  const { weights, cfg } = prepareWeights(raw, name);
  return { weights, cfg, modelName };
}

// ── Scoring ───────────────────────────────────────────────────────────────────

// Extract features for every legal non-true-eye move of `game` and fill
// state.moves / state.logits / state.probs with the softmax of this model.
// Mirrors npat-lib's extract-then-softmax contract so consumers are
// interchangeable.  `game3` is an optional lockstep mirror (avoids a rebuild
// during ladder annotation); `temperature` as in npat-lib (0 = one-hot
// argmax).  Returns state.count.
function computeProbs(game, state, game3, model, temperature = 1) {
  NPat.extractFeatures(game, state, undefined, game3, null);   // raw-key mode
  const n = state.count;
  if (n === 0) return 0;

  const { weights, cfg } = model;
  const tact = state.tact;
  const lg   = state.logits;
  const pr   = state.probs;
  const useTact = cfg.useTactical !== false;
  const NTS  = NPat.N_TACT_SLOTS;

  // Resolve the tactical weights once per call.
  const tW = new Float64Array(NTS);
  if (useTact) {
    for (let k = 0; k < NTS; k++) tW[k] = weights.get(NPat.TACT_RAW_BASE + k) ?? 0;
  }
  const pid33c = cfg.use33c ? state.patIds33c : null;
  const pidP12 = cfg.useP12 ? state.patIdsP12 : null;

  let maxL = -Infinity, maxI = 0;
  for (let i = 0; i < n; i++) {
    let s = 0;
    if (useTact) {
      const tOff = i * NTS;
      for (let k = 0; k < NTS; k++) s += tact[tOff + k] * tW[k];
    }
    if (pid33c) s += weights.get(pid33c[i]) ?? 0;
    if (pidP12) s += weights.get(pidP12[i]) ?? 0;
    lg[i] = s;
    if (s > maxL) { maxL = s; maxI = i; }
  }

  if (temperature === 0) {
    for (let i = 0; i < n; i++) pr[i] = 0;
    pr[maxI] = 1;
    return n;
  }
  const invT = 1 / temperature;
  let sum = 0;
  for (let i = 0; i < n; i++) { pr[i] = Math.exp((lg[i] - maxL) * invT); sum += pr[i]; }
  const inv = 1 / sum;
  for (let i = 0; i < n; i++) pr[i] *= inv;
  return n;
}

// ── Training ──────────────────────────────────────────────────────────────────

// One cross-entropy SGD step toward `target` (array over the state's
// candidates, summing to 1) for the position currently in `state` (as filled
// by computeProbs — raw keys in patIds*, π in probs):
//   Δw[k] = lr · Σ_a (target[a] − π[a]) · count(k, f_a)
// The objective is convex in the weights (linear softmax), so plain SGD
// converges without variance-reduction machinery.
function crossEntropyUpdate(state, model, target, lr) {
  const { weights, cfg } = model;
  const n  = state.count;
  const pr = state.probs;
  const useTact = cfg.useTactical !== false;
  const NTS  = NPat.N_TACT_SLOTS;
  const tact = state.tact;
  const pid33c = cfg.use33c ? state.patIds33c : null;
  const pidP12 = cfg.useP12 ? state.patIdsP12 : null;
  const tacc = useTact ? new Float64Array(NTS) : null;

  for (let i = 0; i < n; i++) {
    const g = lr * (target[i] - pr[i]);
    if (g === 0) continue;
    if (pid33c) { const k = pid33c[i]; weights.set(k, (weights.get(k) ?? 0) + g); }
    if (pidP12) { const k = pidP12[i]; weights.set(k, (weights.get(k) ?? 0) + g); }
    if (useTact) {
      const tOff = i * NTS;
      for (let k = 0; k < NTS; k++) {
        const c = tact[tOff + k];
        if (c !== 0) tacc[k] += g * c;
      }
    }
  }
  if (useTact) {
    for (let k = 0; k < NTS; k++) {
      if (tacc[k] !== 0) {
        const key = NPat.TACT_RAW_BASE + k;
        weights.set(key, (weights.get(key) ?? 0) + tacc[k]);
      }
    }
  }
}

// ── Module exports ────────────────────────────────────────────────────────────

const NPats = {
  VERSION,
  makeWeights,
  freshModel,
  packModel,
  saveModel,
  prepareWeights,
  loadModel,
  computeProbs,
  crossEntropyUpdate,
  // Re-exported so policy consumers need only this module.
  createState: NPat.createState,
};

if (typeof module !== 'undefined') {
  module.exports = NPats;
  require('./npats-lib.test.js').runTests(NPats);
} else {
  window.NPatsLib = NPats;
}

})();
