'use strict';

// BROWSER-COMPATIBLE: no Node.js-only APIs at top level.
// Loaded as a plain <script> tag; do not add require/module/process at top level.

(function () {

// tdsearch2 priors: location-INDEPENDENT twins of the agent's online tables,
// distilled from what its searches conclude (train-tdsearch2-priors.js).
//   actor9:  one weight per (mover, 8-cell code around a point)  — 2 × 6561
//   critic4: one weight per (mover, 2×2 window code)              — 2 × 81
//   critic9: one weight per (mover, 3×3 window code)              — 2 × 19683
// No pattern symmetry: the board is in the orientation it is in.  critic9
// is distilled from the online 3×3 layer, which is switched on only while
// training priors (TD_CRITIC_LAYERS=1,4,9): a move's sims are too few to
// populate 3×3 codes, but thousands of roots are not.
//
// File format: a JS module exporting { actor9, critic4, critic9, comment }
// with the arrays as base64 Float32Array bytes (little-endian).

const A9 = 2 * 6561, C4 = 2 * 81, C9 = 2 * 19683;

function make() {
  return { actor9: new Float32Array(A9), critic4: new Float32Array(C4), critic9: new Float32Array(C9), comment: '' };
}

function encode(arr) {
  const bytes = new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength);
  if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('base64');
  let s = ''; for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}
function decode(b64, length) {
  let bytes;
  if (typeof Buffer !== 'undefined') bytes = new Uint8Array(Buffer.from(b64, 'base64'));
  else { const s = atob(b64); bytes = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i); }
  const out = new Float32Array(length);
  new Uint8Array(out.buffer).set(bytes.subarray(0, length * 4));
  return out;
}

// Priors from a loaded module object (require()d file or window global).
function fromRaw(raw) {
  if (!raw || typeof raw.actor9 !== 'string' || typeof raw.critic4 !== 'string' || typeof raw.critic9 !== 'string') {
    throw new Error('tdsearch2-priors: not a priors file (expected base64 actor9, critic4 and critic9)');
  }
  const p = make();
  p.actor9 = decode(raw.actor9, A9);
  p.critic4 = decode(raw.critic4, C4);
  p.critic9 = decode(raw.critic9, C9);
  p.comment = raw.comment || '';
  return p;
}

function load(filePath) {
  const raw = require(require('path').resolve(filePath));
  return fromRaw(raw);
}

function literal(priors, comment) {
  return `{ comment: ${JSON.stringify(comment || priors.comment || '')}, ` +
         `actor9: "${encode(priors.actor9)}", critic4: "${encode(priors.critic4)}", critic9: "${encode(priors.critic9)}" }`;
}

// Atomic: written to a temp file then renamed, so a reader never sees a
// half-written model.
function save(filePath, priors, comment) {
  const fs = require('fs');
  const src = [
    "'use strict';",
    '// Auto-generated by train-tdsearch2-priors.js — do not edit by hand.',
    `const tdsearch2Priors = ${literal(priors, comment)};`,
    "if (typeof module !== 'undefined') module.exports = tdsearch2Priors;",
    'else window.tdsearch2Priors = tdsearch2Priors;',
  ].join('\n') + '\n';
  const tmp = filePath + '.tmp';
  fs.writeFileSync(tmp, src);
  fs.renameSync(tmp, filePath);
}

const Priors = { A9, C4, C9, make, fromRaw, load, save, literal };
if (typeof module !== 'undefined') module.exports = Priors;
else window.TDSearch2Priors = Priors;

})();
