#!/usr/bin/env node
'use strict';

// train-npat.js — REINFORCE-style policy iterator over nine-pattern features.
//
// Each candidate move is represented by 9 canonical 3×3 pattern IDs (the nine
// windows that overlap the move — see npat-lib.js).  A linear logit policy
//   π(a|s) = softmax( Σ_{p ∈ f_a} w[p] )
// is trained by REINFORCE on the game's terminal outcome.
//
// Per-step update (for the mover at step t):
//   Δw[p] = lr · A_t · ( count(p, f_{a_t}) − Σ_i π(i|s_t) · count(p, f_i) )
// where A_t = R_t − b   (R_t ∈ {−1, 0, +1} from mover's perspective, b is an
// EMA of past rewards as a REINFORCE baseline (variance reduction).
//
// Weights are stored sparsely in a Map<pid, weight>.  They are saved at every
// progress print (interval grows geometrically).  Ctrl-C to stop.
//
// Usage:
//   node train-npat.js [--size 9] [--lr 0.02] [--reward-ema 0.99]
//                      [--load path] [--save path] [--eval-agent random]

const path = require('path');
const fs   = require('fs');

const { Game2, BLACK, PASS } = require('./game2.js');
const { Game3 } = require('./game3.js');
const NPat = require('./npat-lib.js');
const Util = require('./util.js');

// ── Arguments ─────────────────────────────────────────────────────────────────

const opts       = Util.parseArgs(process.argv.slice(2),
  ['help', 'no-tactical', 'force-tactical-limit', 'use-3x3c', 'use-p12']);
const TRAIN_SIZE = parseInt(opts['train-size'] || opts.size || '9', 10);
const EVAL_SIZE  = parseInt(opts['eval-size']  || opts.size || opts['train-size'] || '13', 10);
const LR         = parseFloat(opts.lr || '0.02');
const REWARD_EMA = parseFloat(opts['reward-ema'] || '0.99');   // EMA decay for the reward baseline (variance reduction); 0 disables
const TEMPERATURE = Math.max(0, parseFloat(opts.temperature || '1'));
const USE_33C    = !!opts['use-3x3c'];                        // enable centered 3×3 window
const USE_P12    = !!opts['use-p12'];                          // enable 12-cell diamond shape window
const USE_TACT   = !opts['no-tactical'];                       // tactical features (default ON)
const EVAL_AGENT = opts.eval || opts['eval-agent'] || 'random';
const SAVE_PATH  = opts.save || `out/npat-${Math.random().toString(36).slice(2, 10)}.js`;
const LOAD_PATH  = opts.load || null;

// ── Weights ───────────────────────────────────────────────────────────────────

let weights = NPat.createWeights({ useTactical: USE_TACT, use33c: USE_33C, useP12: USE_P12 });
let ema     = 0;                     // EMA of terminal outcome from mover's perspective
let totalUpdates = 0;                // cumulative weight-update count across resumed runs

// ── Persistence ───────────────────────────────────────────────────────────────

function saveWeights(filePath, w, meta) {
  const source = w.vals;
  const parts = [];
  for (const [rawId, denseIdx] of w.map) {
    parts.push(`[${JSON.stringify(rawId)},${+source[denseIdx].toFixed(6)}]`);
  }
  const list = '[' + parts.join(',') + ']';
  const src = [
    "'use strict';",
    '// Auto-generated by train-npat.js — do not edit by hand.',
    `const npatModel = {`,
    `  ema: ${+meta.ema.toFixed(6)},`,
    `  totalUpdates: ${Math.round(meta.totalUpdates)},`,
    `  tactStoneLimit: ${NPat.TACT_STONE_LIMIT},`,
    `  weights: new Map(${list}),`,
    `};`,
    "if (typeof module !== 'undefined') module.exports = npatModel;",
    "else window.npatModel = npatModel;",
  ].join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, src);
}

function loadWeights(filePath) {
  delete require.cache[require.resolve(path.resolve(filePath))];
  const raw = require(path.resolve(filePath));
  if (raw.tactStoneLimit !== undefined && raw.tactStoneLimit !== NPat.TACT_STONE_LIMIT) {
    if (opts['force-tactical-limit']) {
      console.warn(
        `WARNING: tactStoneLimit mismatch — file ${path.basename(filePath)} ` +
        `was trained at ${raw.tactStoneLimit}, current is ${NPat.TACT_STONE_LIMIT}. ` +
        `Continuing anyway (--force-tactical-limit). Existing tactical weights ` +
        `will have scrambled slot semantics until retrained.`
      );
    } else {
      throw new Error(
        `TACT_STONE_LIMIT mismatch: file was trained with ${raw.tactStoneLimit}, ` +
        `current is ${NPat.TACT_STONE_LIMIT}. ` +
        `Re-run with NPAT_STONE_LIMIT=${raw.tactStoneLimit}, or pass --force-tactical-limit.`
      );
    }
  }
  const w = NPat.createWeights({
    initialCapacity: Math.max(1024, raw.weights.size | 0),
    useTactical: USE_TACT, use33c: USE_33C, useP12: USE_P12,
  });
  for (const [rawId, val] of raw.weights) {
    const idx = NPat.internWeight(w, rawId);
    w.vals[idx] = val;
  }
  // Older save files truncated totalUpdates to int32; clamp away negatives.
  const tu = raw.totalUpdates ?? 0;
  return { weights: w, ema: raw.ema ?? 0, totalUpdates: tu < 0 ? 0 : tu, tactStoneLimit: raw.tactStoneLimit };
}

// ── Training ──────────────────────────────────────────────────────────────────

// Play one self-play game and apply REINFORCE updates after it ends.
// Returns game-level stats for logging.
function trainGame(N) {
  const game  = new Game2(N, false);
  const game3 = new Game3(N);  // kept in lockstep for ladder analysis
  const maxMoves = N * N * 4;
  const tStart   = Date.now();

  // Per-step record: enough to replay the gradient with the known outcome.
  // We store (player, chosenIndex, per-shape patIds, tact, probs, count).
  // To minimise allocations we use per-step state snapshots.
  const steps = [];
  const state = NPat.createState(N);

  let moves = 0;
  while (!game.gameOver && moves < maxMoves) {
    const player = game.current;
    const choice = NPat.policyMove(game, state, weights, Math, game3, TEMPERATURE);

    if (choice.index >= 0) {
      // Snapshot features + distribution (copy just the slice we need).
      // We reuse state.touched across snapshots as the REINFORCE scratch
      // buffer — reinforceUpdate zeros each touched slot after applying.
      const n = state.count;
      const patIds33c = new Int32Array(n);
      patIds33c.set(state.patIds33c.subarray(0, n));
      const patIdsP12 = new Int32Array(n);
      patIdsP12.set(state.patIdsP12.subarray(0, n));
      const tact = new Uint8Array(n * NPat.N_TACT_SLOTS);
      tact.set(state.tact.subarray(0, n * NPat.N_TACT_SLOTS));
      const probs = new Float64Array(n);
      probs.set(state.probs.subarray(0, n));
      steps.push({ player, chosenIndex: choice.index, count: n, patIds33c, patIdsP12, tact, probs, touched: state.touched });
    }

    game.play(choice.move);
    game3.play(choice.move);
    moves++;
  }

  // Terminal outcome: +1 if BLACK wins else -1 (use calcWinner; ties → 0).
  const winner = game.calcWinner();
  const outcomeBlack = winner === BLACK ? 1 : (winner === 0 ? 0 : -1);

  // REINFORCE: apply Δw per step with advantage = R − rewardBaseline, where R
  // is from the MOVER'S perspective.
  let stepsApplied = 0;
  let weightUpdates = 0;
  for (const s of steps) {
    const R = s.player === BLACK ? outcomeBlack : -outcomeBlack;
    const adv = REWARD_EMA > 0 ? (R - ema) : R;
    weightUpdates += NPat.reinforceUpdate(s, s.chosenIndex, adv, weights, LR) || 0;
    stepsApplied++;
  }

  if (REWARD_EMA > 0 && steps.length > 0) {
    // Update EMA towards the black-perspective outcome (so it's consistent).
    // Note: we subtract ema from mover-perspective R in the step update, which
    // is a small approximation — the baseline is still unbiased only if it is
    // independent of mover.  In practice the asymmetry washes out quickly.
    ema = REWARD_EMA * ema + (1 - REWARD_EMA) * outcomeBlack;
  }

  // Sum of max(softmax) across the snapshotted steps (top-1 confidence).
  let maxProbSum = 0, maxProbN = 0;
  for (const s of steps) {
    let mx = 0;
    const p = s.probs;
    const n = s.count;
    for (let i = 0; i < n; i++) if (p[i] > mx) mx = p[i];
    maxProbSum += mx;
    maxProbN++;
  }

  return {
    elapsedMs: Date.now() - tStart,
    moves,
    stepsApplied,
    weightUpdates,
    outcomeBlack,
    maxProbSum,
    maxProbN,
  };
}

// ── Evaluation against a reference agent ─────────────────────────────────────

function evalVsReference(N, refGetMove, nGames) {
  const state = NPat.createState(N);
  const results = [];
  for (let g = 0; g < nGames; g++) {
    const policyIsBlack = (g % 2 === 0);
    const game  = new Game2(N, false);
    const game3 = new Game3(N);  // lockstep copy for ladder analysis
    const maxMoves = N * N * 4;
    let m = 0;
    while (!game.gameOver && m++ < maxMoves) {
      let idx;
      if ((game.current === BLACK) === policyIsBlack) {
        idx = NPat.greedyMove(game, state, weights, game3);
      } else {
        const mv = refGetMove(game);
        idx = mv && mv.move !== undefined ? mv.move : PASS;
      }
      game.play(idx);
      game3.play(idx);
    }
    const winner = game.calcWinner();
    results.push((winner === BLACK) === policyIsBlack ? 1 : 0);
  }
  return results;
}

// ── CLI setup ─────────────────────────────────────────────────────────────────

if (opts.help) {
  console.log(`Usage: node train-npat.js [options]
  --size N         | --train-size N (default 9) | --eval-size N (default 13)
  --lr F           learning rate (default 0.02)
  --reward-ema F   EMA decay for the reward baseline (variance reduction).
                   Default 0.99; 0 disables.
  --temperature F  softmax sampling temperature for training moves;
                   0 = argmax, 1 = standard softmax (default 1)
  --use-3x3c       enable the centered 3×3 shape window (default off)
  --use-p12        enable the 12-cell diamond shape window (default off)
  --no-tactical    disable the ladder/tactical features (default on)
  --eval-agent S   reference agent in ai/ (default random)
  --load PATH      resume from saved weights
  --save PATH      where to save (default out/npat-<rand>.js)
`);
  process.exit(0);
}

const { getMove: evalGetMove } =
  require(path.join(__dirname, 'ai', EVAL_AGENT + '.js'));

if (LOAD_PATH) {
  if (fs.existsSync(LOAD_PATH)) {
    const loaded = loadWeights(LOAD_PATH);
    weights = loaded.weights;
    ema     = loaded.ema;
    totalUpdates = loaded.totalUpdates;
    console.log(`Loaded ${weights.size} weights from ${LOAD_PATH}  (ema=${ema.toFixed(3)}, totalUpdates=${totalUpdates})`);
  } else {
    console.warn(`Warning: --load file not found: ${LOAD_PATH}`);
  }
}

console.log(`lr=${LR}  reward-ema=${REWARD_EMA}  temperature=${TEMPERATURE}`);
console.log(`features: tactical=${USE_TACT ? 'ON' : 'off'}  3x3c=${USE_33C ? 'ON' : 'off'}  p12=${USE_P12 ? 'ON' : 'off'}`);
console.log(`train-size=${TRAIN_SIZE}  eval-size=${EVAL_SIZE}  ref=${EVAL_AGENT}`);
console.log(`Out: ${SAVE_PATH}${LOAD_PATH ? `  (resumed from ${LOAD_PATH})` : ''}`);
console.log();

console.log([
  'game'.padStart(4),
  'tElp'.padStart(5),
  'tGm '.padStart(5),
  'nWts'.padStart(4),
  'avgW'.padStart(6),
  'u/pa'.padStart(4),
  'maxP'.padStart(4),
  'gRef'.padStart(4),
  'wrRf'.padStart(4),
  'wrAv'.padStart(4),
].join('  '));

// ── Main loop ─────────────────────────────────────────────────────────────────

const t0 = Date.now();
let nextPrintAt = t0 + 1000;
let lastPrintAt = t0;
let g = 0;
let maxProbSumWindow = 0, maxProbNWindow = 0;
let lastPrintG = 0;
let elapsedMsAcc = 0;
const evalHistory = [];   // per-game eval results (1 / 0); rolling-half avgWR uses this

while (true) {
  g++;
  const r = trainGame(TRAIN_SIZE);
  totalUpdates += r.weightUpdates;
  maxProbSumWindow += r.maxProbSum;
  maxProbNWindow   += r.maxProbN;
  elapsedMsAcc     += r.elapsedMs;

  if (Date.now() >= nextPrintAt) {
    // Count only interned pids that have received a non-zero gradient: pids
    // are interned on first sight in extractFeatures, so weights.size counts
    // every pattern ever seen — the "learned" count is the non-zero subset.
    let wAbsSum = 0, wNonZero = 0;
    const vals = weights.vals;
    const wN   = weights.size;
    for (let i = 0; i < wN; i++) {
      const a = Math.abs(vals[i]);
      if (a === 0) continue;
      wNonZero++;
      wAbsSum += a;
    }
    const wAvg    = wNonZero > 0 ? wAbsSum / wNonZero : 0;
    const updPerPat = wNonZero > 0 ? totalUpdates / wNonZero : 0;

    const nextMs = Date.now() - t0;

    const maxPAvg = maxProbNWindow > 0 ? maxProbSumWindow / maxProbNWindow : 0;

    // Eval vs reference for up to 20% of the interval's training time, capped
    // at 1000 games.  greedy npat policy on this side vs evalGetMove on the
    // other side, colours alternating.
    const intervalMs   = Date.now() - lastPrintAt;
    const evalBudgetMs = intervalMs * 0.2;
    const evalStart    = Date.now();
    let evalWins = 0, evalGames = 0;
    while (evalGames < 1000 && Date.now() - evalStart < evalBudgetMs) {
      const results = evalVsReference(EVAL_SIZE, evalGetMove, 1);
      evalHistory.push(results[0]);
      evalWins += results[0];
      evalGames++;
    }
    const avgHalf = Math.max(1, Math.floor(evalHistory.length / 2));
    const avgWR   = evalHistory.length > 0
      ? evalHistory.slice(-avgHalf).reduce((s, r) => s + r, 0) / avgHalf
      : 0;
    const wrRefStr = evalGames > 0 ? (evalWins / evalGames).toFixed(3) : '-';

    const elapsedMs      = Date.now() - t0;
    const cycleN         = g - lastPrintG;
    const cycleAvgGameMs = cycleN > 0 ? elapsedMsAcc / cycleN : 0;

    console.log([
      Util.fmt4(g),
      Util.fmtMs(elapsedMs),
      Util.fmtMs(cycleAvgGameMs),
      Util.fmt4(wNonZero),
      wAvg.toFixed(4).padStart(6),
      Util.fmt4(updPerPat),
      Util.fmtRatio4(maxPAvg),
      Util.fmt4(evalGames),
      evalGames > 0 ? Util.fmtRatio4(evalWins / evalGames) : '   -',
      evalHistory.length > 0 ? Util.fmtRatio4(avgWR) : '   -',
    ].join('  '));
    maxProbSumWindow = 0; maxProbNWindow = 0;
    elapsedMsAcc = 0;
    lastPrintG = g;

    saveWeights(SAVE_PATH, weights, { ema, totalUpdates });
    nextPrintAt = t0 + Math.round(nextMs * 1.4);
    lastPrintAt = Date.now();
  }
}
