#!/usr/bin/env node
'use strict';

// train-npat.js — REINFORCE-style policy iterator over nine-pattern features.
//
// Each candidate move is represented by 9 canonical 3×3 pattern IDs (the nine
// windows that overlap the move — see npat-lib.js).  A linear logit policy
//   π(a|s) = softmax( Σ_{p ∈ f_a} w[p] )
// is trained by REINFORCE on the game's terminal outcome.
//
// Per-step update (for the mover at step t):
//   Δw[p] = lr · A_t · ( count(p, f_{a_t}) − Σ_i π(i|s_t) · count(p, f_i) )
// where A_t = R_t − b   (R_t ∈ {−1, 0, +1} from mover's perspective, b is an
// exponential-moving-average baseline to reduce variance).
//
// Weights are stored sparsely in a Map<pid, weight>.  They are saved at every
// progress print (interval grows geometrically).  Ctrl-C to stop.
//
// Usage:
//   node train-npat.js [--size 9] [--lr 0.05] [--baseline 0.95]
//                      [--load path] [--save path] [--eval-agent random]

const path = require('path');
const fs   = require('fs');

const { Game2, BLACK, PASS } = require('./game2.js');
const { Game3 } = require('./game3.js');
const NPat = require('./npat-lib.js');
const Util = require('./util.js');

// ── Arguments ─────────────────────────────────────────────────────────────────

const opts       = Util.parseArgs(process.argv.slice(2), ['help']);
const TRAIN_SIZE = parseInt(opts['train-size'] || opts.size || '9', 10);
const EVAL_SIZE  = parseInt(opts['eval-size']  || opts.size || opts['train-size'] || '9', 10);
const LR         = parseFloat(opts.lr || '0.05');
const BASELINE   = parseFloat(opts.baseline || '0.95');   // EMA decay for reward baseline; 0 disables
const EPSILON    = Math.min(parseFloat(opts.epsilon || '0.0'), 0.9999);
const BETA       = parseFloat(opts.beta || '0.0');          // entropy-bonus coefficient; 0 disables
const EVAL_AGENT = opts.eval || opts['eval-agent'] || 'random';
const SAVE_PATH  = opts.save || `out/npat-${Math.random().toString(36).slice(2, 10)}.js`;
const LOAD_PATH  = opts.load || null;

// ── Weights ───────────────────────────────────────────────────────────────────

let weights = NPat.createWeights();  // raw canonKey → dense idx; vals/delta by idx
let ema     = 0;                     // EMA of terminal outcome from mover's perspective

// ── Persistence ───────────────────────────────────────────────────────────────

function saveWeights(filePath, w, meta) {
  const parts = [];
  for (const [rawId, denseIdx] of w.map) {
    parts.push(`[${rawId},${+w.vals[denseIdx].toFixed(6)}]`);
  }
  const list = '[' + parts.join(',') + ']';
  const src = [
    "'use strict';",
    '// Auto-generated by train-npat.js — do not edit by hand.',
    `const npatModel = {`,
    `  ema: ${+meta.ema.toFixed(6)},`,
    `  weights: new Map(${list}),`,
    `};`,
    "if (typeof module !== 'undefined') module.exports = npatModel;",
    "else window.npatModel = npatModel;",
  ].join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, src);
}

function loadWeights(filePath) {
  delete require.cache[require.resolve(path.resolve(filePath))];
  const raw = require(path.resolve(filePath));
  const w = NPat.createWeights(Math.max(1024, raw.weights.size | 0));
  for (const [rawId, val] of raw.weights) {
    const idx = NPat.internWeight(w, rawId);
    w.vals[idx] = val;
  }
  return { weights: w, ema: raw.ema ?? 0 };
}

// ── Training ──────────────────────────────────────────────────────────────────

// Play one self-play game and apply REINFORCE updates after it ends.
// Returns game-level stats for logging.
function trainGame(N) {
  const game  = new Game2(N, false);
  const game3 = new Game3(N);  // kept in lockstep for ladder analysis
  const maxMoves = N * N * 4;
  const tStart   = Date.now();

  // Per-step record: enough to replay the gradient with the known outcome.
  // We store (player, chosenIndex, patIds (9*count), probs (count), moves (count), count).
  // To minimise allocations we use per-step state snapshots.
  const steps = [];
  const state = NPat.createState(N);

  let moves = 0;
  while (!game.gameOver && moves < maxMoves) {
    const player = game.current;
    let choice;

    if (EPSILON > 0 && Math.random() < EPSILON) {
      // Uniform exploration over legal non-eye moves.  Still need features
      // (and π) for the gradient, so run the same extraction path.
      const mv = NPat.policyMove(game, state, weights, Math, game3);
      if (state.count === 0) { choice = { move: PASS, index: -1, prob: 1 }; }
      else {
        const i = Math.floor(Math.random() * state.count);
        choice = { move: state.moves[i], index: i, prob: state.probs[i] };
      }
    } else {
      choice = NPat.policyMove(game, state, weights, Math, game3);
    }

    if (choice.index >= 0) {
      // Snapshot features + distribution (copy just the slice we need).
      // We reuse state.touched across snapshots as the REINFORCE scratch
      // buffer — reinforceUpdate zeros each touched slot after applying.
      const n = state.count;
      const patIds = new Int32Array(n * 9);
      patIds.set(state.patIds.subarray(0, n * 9));
      const patIds34 = new Int32Array(n * NPat.WINDOWS_34);
      patIds34.set(state.patIds34.subarray(0, n * NPat.WINDOWS_34));
      const tact = new Uint8Array(n * NPat.N_TACT);
      tact.set(state.tact.subarray(0, n * NPat.N_TACT));
      const probs = new Float64Array(n);
      probs.set(state.probs.subarray(0, n));
      steps.push({ player, chosenIndex: choice.index, count: n, patIds, patIds34, tact, probs, touched: state.touched });
    }

    game.play(choice.move);
    game3.play(choice.move);
    moves++;
  }

  // Terminal outcome: +1 if BLACK wins else -1 (use calcWinner; ties → 0).
  const winner = game.calcWinner();
  const outcomeBlack = winner === BLACK ? 1 : (winner === 0 ? 0 : -1);

  // REINFORCE: apply Δw per step with advantage = R − baseline, where R is from
  // the MOVER'S perspective.
  let stepsApplied = 0;
  for (const s of steps) {
    const R = s.player === BLACK ? outcomeBlack : -outcomeBlack;
    const adv = BASELINE > 0 ? (R - ema) : R;
    NPat.reinforceUpdate(s, s.chosenIndex, adv, weights, LR);
    if (BETA > 0) NPat.entropyBonusUpdate(s, weights, LR * BETA);
    stepsApplied++;
  }

  if (BASELINE > 0 && steps.length > 0) {
    // Update EMA towards the black-perspective outcome (so it's consistent).
    // Note: we subtract ema from mover-perspective R in the step update, which
    // is a small approximation — the baseline is still unbiased only if it is
    // independent of mover.  In practice the asymmetry washes out quickly.
    ema = BASELINE * ema + (1 - BASELINE) * outcomeBlack;
  }

  return {
    elapsedMs: Date.now() - tStart,
    moves,
    stepsApplied,
    outcomeBlack,
  };
}

// ── Evaluation against a reference agent ─────────────────────────────────────

function evalVsReference(N, refGetMove, nGames) {
  const state = NPat.createState(N);
  const results = [];
  for (let g = 0; g < nGames; g++) {
    const policyIsBlack = (g % 2 === 0);
    const game  = new Game2(N, false);
    const game3 = new Game3(N);  // lockstep copy for ladder analysis
    const maxMoves = N * N * 4;
    let m = 0;
    while (!game.gameOver && m++ < maxMoves) {
      let idx;
      if ((game.current === BLACK) === policyIsBlack) {
        idx = NPat.greedyMove(game, state, weights, game3);
      } else {
        const mv = refGetMove(game);
        idx = mv && mv.move !== undefined ? mv.move : PASS;
      }
      game.play(idx);
      game3.play(idx);
    }
    const winner = game.calcWinner();
    results.push((winner === BLACK) === policyIsBlack ? 1 : 0);
  }
  return results;
}

// ── CLI setup ─────────────────────────────────────────────────────────────────

if (opts.help) {
  console.log(`Usage: node train-npat.js [options]
  --size N         | --train-size N | --eval-size N   (default 9)
  --lr F           learning rate (default 0.05)
  --baseline F     EMA decay for reward baseline (default 0.95; 0 disables)
  --epsilon F      uniform-random exploration rate (default 0)
  --beta F         entropy-bonus coefficient (default 0; applied on top of lr)
  --eval-agent S   reference agent in ai/ (default random)
  --load PATH      resume from saved weights
  --save PATH      where to save (default out/npat-<rand>.js)
`);
  process.exit(0);
}

const { getMove: evalGetMove } =
  require(path.join(__dirname, 'ai', EVAL_AGENT + '.js'));

if (LOAD_PATH) {
  if (fs.existsSync(LOAD_PATH)) {
    const loaded = loadWeights(LOAD_PATH);
    weights = loaded.weights;
    ema     = loaded.ema;
    console.log(`Loaded ${weights.size} weights from ${LOAD_PATH}  (ema=${ema.toFixed(3)})`);
  } else {
    console.warn(`Warning: --load file not found: ${LOAD_PATH}`);
  }
}

console.log(`lr=${LR}  baseline=${BASELINE}  epsilon=${EPSILON}  beta=${BETA}`);
console.log(`train-size=${TRAIN_SIZE}  eval-size=${EVAL_SIZE}  ref=${EVAL_AGENT}`);
console.log(`Out: ${SAVE_PATH}${LOAD_PATH ? `  (resumed from ${LOAD_PATH})` : ''}`);
console.log();

console.log([
  'game'   .padStart(7),
  'elapsed'.padStart(8),
  'tGameMs'.padStart(7),
  'weights'.padStart(8),
  'win%'   .padStart(6) + '(' + 'n'.padStart(3) + ')',
  'winAvg%'.padStart(7),
  'avglen' .padStart(6),
  'ema'    .padStart(6),
  'avg|w|' .padStart(7),
  'max|w|' .padStart(7),
  'tTrain' .padStart(7),
  'tTest'  .padStart(6),
].join('  '));

// ── Main loop ─────────────────────────────────────────────────────────────────

const t0 = Date.now();
let nextPrintAt = t0 + 1000;
let g = 0;
let intervalGames = 0, intervalMoves = 0, intervalTrainMs = 0;
const evalHistory = [];

while (true) {
  g++;
  const { moves, elapsedMs } = trainGame(TRAIN_SIZE);
  intervalGames++;
  intervalMoves   += moves;
  intervalTrainMs += elapsedMs;

  if (Date.now() >= nextPrintAt) {
    const tTestStart = Date.now();
    const batch = [];
    while (true) {
      for (const r of evalVsReference(EVAL_SIZE, evalGetMove, 2)) batch.push(r);
      const tMs = Date.now() - tTestStart;
      if (tMs > 0.3 * intervalTrainMs || batch.length >= 998) break;
    }
    for (const r of batch) evalHistory.push(r);

    const latestWR = batch.length ? batch.reduce((s, r) => s + r, 0) / batch.length : 0;
    const half     = Math.max(1, Math.floor(evalHistory.length / 2));
    const avgWR    = evalHistory.slice(-half).reduce((s, r) => s + r, 0) / half;
    const avgLen   = (intervalMoves / Math.max(1, intervalGames)).toFixed(1);
    const tGameMs  = (intervalTrainMs / Math.max(1, intervalGames)).toFixed(1);

    intervalGames   = 0;
    intervalMoves   = 0;

    // Count only interned pids that have received a non-zero gradient: pids
    // are interned on first sight in extractFeatures, so weights.size counts
    // every pattern ever seen — the "learned" count is the non-zero subset.
    let wAbsSum = 0, wAbsMax = 0, wNonZero = 0;
    const vals = weights.vals;
    const wN   = weights.size;
    for (let i = 0; i < wN; i++) {
      const a = Math.abs(vals[i]);
      if (a === 0) continue;
      wNonZero++;
      wAbsSum += a;
      if (a > wAbsMax) wAbsMax = a;
    }
    const wAvg = wNonZero > 0 ? wAbsSum / wNonZero : 0;

    const tTestMs   = Date.now() - tTestStart;
    const elapsedS  = ((Date.now() - t0) / 1000).toFixed(0);
    const nextMs    = Date.now() - t0;
    const tTrainStr = (intervalTrainMs / 1000).toFixed(1) + 's';
    intervalTrainMs = 0;

    console.log([
      String(g)                                  .padStart(7),
      elapsedS                                   .padStart(8),
      tGameMs                                    .padStart(7),
      String(wNonZero)                           .padStart(8),
      ((100 * latestWR).toFixed(1) + '%')        .padStart(6) + '(' + String(batch.length).padStart(3) + ')',
      ((100 * avgWR).toFixed(1) + '%')           .padStart(7),
      avgLen                                     .padStart(6),
      ema.toFixed(3)                             .padStart(6),
      wAvg.toFixed(3)                            .padStart(7),
      wAbsMax.toFixed(3)                         .padStart(7),
      tTrainStr                                  .padStart(7),
      ((tTestMs / 1000).toFixed(1) + 's')        .padStart(6),
    ].join('  '));

    saveWeights(SAVE_PATH, weights, { ema });
    nextPrintAt = t0 + Math.round(nextMs * 1.4);
  }
}
