#!/usr/bin/env node
'use strict';

// train-cotrain.js — co-train npat and vlibpat from scratch.
//
// At each step in self-play:
//   1. npat computes softmax over legal moves.
//   2. Bernoulli-sample candidates with p = npat probability.  Always force-
//      include npat's argmax so the candidate set is non-empty.
//   3. vlibpat evaluates V on each candidate's resulting position; pick the
//      argmax (BLACK maximises V, WHITE minimises) — no dither.
//   4. Play the chosen move.
//
// Updates after the game ends:
//   • vlibpat: 2-step logistic TD with absolute targets (P(BLACK wins)).
//   • npat: cross-entropy with the move vlibpat picked at each step
//     (NPat.reinforceUpdate with advantage = +1).
//
// Both colours use the combined policy.  No --ext.  Random ε-moves explore
// without triggering vlibpat or npat updates at that step.

const path = require('path');
const fs   = require('fs');

const { Game2, BLACK, PASS } = require('./game2.js');
const { Game3, game3FromGame2 } = require('./game3.js');
const { extractFeatures, evaluateFeatures, prepareSpecs } = require('./vlibpat.js');
const NPat = require('./npat-lib.js');
const Util = require('./util.js');

// ── Arguments ─────────────────────────────────────────────────────────────────

const opts = Util.parseArgs(process.argv.slice(2), ['help']);
if (opts.help) {
  console.log(`Usage: node train-cotrain.js [options]
  --size N             board size (default 9)
  --vlibpat-lr F       vlibpat learning rate (default 0.3)
  --npat-lr F          npat learning rate (default 0.05)
  --epsilon F          random-move probability, no training (default 0.1)
  --top-k N            number of top-probability moves to include as candidates (default 10)
  --full-width-rate F  fraction of steps that use full-width search instead of filter (default 0.01)
  --temperature F      softmax temperature on oracle logits for npat soft target (default 1.0)
  --ema-alpha F        Polyak EMA decay per game for vlibpat (default 0.9)
  --npat-ema-alpha F   Polyak EMA decay per game for npat (default 0.999)
  --print-every N      print cadence in games (default 100)
  --limit N            stop after N games (default: forever)
  --vlibpat-save P     vlibpat output (default out/cotrain-vlibpat-<rand>.js)
  --npat-save P        npat    output (default out/cotrain-npat-<rand>.js)
  --vlibpat-load P     resume vlibpat from this file (optional)
  --npat-load P        resume npat from this file (optional)
`);
  process.exit(0);
}
const TRAIN_SIZE      = parseInt(opts['train-size'] || opts.size || '9', 10);
const VLIBPAT_LR      = parseFloat(opts['vlibpat-lr'] || '0.3');
const NPAT_LR         = parseFloat(opts['npat-lr']    || '0.05');
const EPSILON         = Math.min(parseFloat(opts.epsilon || '0.1'), 0.9999);
const TOP_K = parseInt(opts['top-k'] || '10', 10);
const FULL_WIDTH_RATE = parseFloat(opts['full-width-rate'] || '0.01');
const TEMPERATURE     = parseFloat(opts['temperature'] || '1.0');
const EMA_ALPHA       = parseFloat(opts['ema-alpha']      || '0.9');
const NPAT_EMA_ALPHA  = parseFloat(opts['npat-ema-alpha'] || '0.999');
const PRINT_EVERY     = parseInt(opts['print-every'] || '100', 10);
const LIMIT_GAMES     = opts.limit !== undefined ? parseInt(opts.limit, 10) : 0;
const VLIBPAT_SAVE    = opts['vlibpat-save'] || `out/cotrain-vlibpat-${Math.random().toString(36).slice(2, 10)}.js`;
const NPAT_SAVE       = opts['npat-save']    || `out/cotrain-npat-${Math.random().toString(36).slice(2, 10)}.js`;
const VLIBPAT_LOAD    = opts['vlibpat-load'] || null;
const NPAT_LOAD       = opts['npat-load']    || null;

const VLIBPAT_SPECS = [
  { size: 2 },
  { size: 3 },
  { size: 3, ladder: false },
];

// ── vlibpat state ────────────────────────────────────────────────────────────

let vlibpatSpecs = VLIBPAT_SPECS;
let vlibpatPrep  = prepareSpecs(vlibpatSpecs);
let vlibpatW     = new Map();      // key (int) → weight
let vlibpatWEMA  = new Map();      // EMA shadow
let vlibpatWEMAInit = false;

function applyVlibpatEMA(alpha) {
  if (!vlibpatWEMAInit) {
    for (const [k, v] of vlibpatW) vlibpatWEMA.set(k, v);
    vlibpatWEMAInit = true;
    return;
  }
  for (const [k, v] of vlibpatW) {
    const e = vlibpatWEMA.get(k);
    if (e === undefined) vlibpatWEMA.set(k, v);
    else                  vlibpatWEMA.set(k, alpha * e + (1 - alpha) * v);
  }
}

function saveVlibpat(filePath) {
  const src = vlibpatWEMAInit ? vlibpatWEMA : vlibpatW;
  const parts = [];
  for (const [k, v] of src) {
    parts.push(`[${k},${+v.toFixed(6)}]`);
  }
  const list = '[' + parts.join(',') + ']';
  const body = [
    "'use strict';",
    '// Auto-generated by train-cotrain.js — do not edit by hand.',
    `const vlibpatModel = { specs: ${JSON.stringify(vlibpatSpecs)}, weights: new Map(${list}) };`,
    "if (typeof module !== 'undefined') module.exports = vlibpatModel;",
    "else window.vlibpatModel = vlibpatModel;",
  ].join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, body);
}

function loadVlibpat(filePath) {
  delete require.cache[require.resolve(path.resolve(filePath))];
  const raw = require(path.resolve(filePath));
  vlibpatSpecs = raw.specs;
  vlibpatPrep  = prepareSpecs(vlibpatSpecs);
  vlibpatW     = new Map();
  vlibpatWEMA  = new Map();
  for (const [k, v] of raw.weights) {
    vlibpatW.set(k, v);
    vlibpatWEMA.set(k, v);
  }
  vlibpatWEMAInit = true;
  console.log(`Loaded ${vlibpatW.size} vlibpat weights from ${filePath}  specs=${JSON.stringify(vlibpatSpecs)}`);
}

if (VLIBPAT_LOAD) loadVlibpat(VLIBPAT_LOAD);

// ── npat state ───────────────────────────────────────────────────────────────

const NPAT_USE_33C = true;
const NPAT_USE_E   = false;
const NPAT_USE_TACT = true;

let npatWeights = NPat.createWeights({ useTactical: NPAT_USE_TACT, use33c: NPAT_USE_33C, useE: NPAT_USE_E });
let npatTotalUpdates = 0;

function saveNpat(filePath) {
  const useEMA = npatWeights.valsEMAInit;
  const source = useEMA ? npatWeights.valsEMA : npatWeights.vals;
  const parts = [];
  for (const [rawId, denseIdx] of npatWeights.map) {
    parts.push(`[${JSON.stringify(rawId)},${+source[denseIdx].toFixed(6)}]`);
  }
  const list = '[' + parts.join(',') + ']';
  const body = [
    "'use strict';",
    '// Auto-generated by train-cotrain.js — do not edit by hand.',
    `const npatModel = {`,
    `  totalUpdates: ${Math.round(npatTotalUpdates)},`,
    `  tactStoneLimit: ${NPat.TACT_STONE_LIMIT},`,
    `  emaAlpha: ${+NPAT_EMA_ALPHA.toFixed(6)},`,
    `  weightsAreEMA: ${useEMA},`,
    `  weights: new Map(${list}),`,
    `};`,
    "if (typeof module !== 'undefined') module.exports = npatModel;",
    "else window.npatModel = npatModel;",
  ].join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, body);
}

function loadNpat(filePath) {
  delete require.cache[require.resolve(path.resolve(filePath))];
  const raw = require(path.resolve(filePath));
  if (raw.tactStoneLimit !== undefined && raw.tactStoneLimit !== NPat.TACT_STONE_LIMIT) {
    throw new Error(`npat TACT_STONE_LIMIT mismatch: file=${raw.tactStoneLimit} runtime=${NPat.TACT_STONE_LIMIT}`);
  }
  const w = NPat.createWeights({
    initialCapacity: Math.max(1024, raw.weights.size | 0),
    useTactical: NPAT_USE_TACT, use33c: NPAT_USE_33C, useE: NPAT_USE_E,
  });
  for (const [rawId, val] of raw.weights) {
    const idx = NPat.internWeight(w, rawId);
    w.vals[idx] = val;
    w.valsEMA[idx] = val;
  }
  w.valsEMAInit = true;
  npatWeights = w;
  npatTotalUpdates = raw.totalUpdates ?? 0;
  console.log(`Loaded ${npatWeights.size} npat weights from ${filePath}`);
}

if (NPAT_LOAD) loadNpat(NPAT_LOAD);

// ── vlibpat TD update ────────────────────────────────────────────────────────

function tdUpdate(features, target, lr) {
  const n = features.count;
  if (n === 0) return;
  const perFeature = (target - features.val) / n;
  const step = lr * perFeature;
  const { keys, pols } = features;
  for (let i = 0; i < n; i++) {
    const k = keys[i];
    vlibpatW.set(k, (vlibpatW.get(k) ?? 0) + pols[i] * step);
  }
}

function absoluteOutcome(game) {
  return game.calcWinner() === BLACK ? 1 : 0;
}

// ── Soft-target gradient (value-based distillation): ────────────────────────
//   Δw_k = lr · Σ_i (π_target(i) - π_npat(i)) · feat_k(i)

function softTargetUpdate(state, targetProbs, w, lr) {
  const n = state.count;
  if (n === 0) return 0;
  const probs = state.probs;
  const tact  = state.tact;
  const vals  = w.vals;
  const delta = w.delta;
  const tIds  = w.tactIds;
  const touched = state.touched;
  const cfg   = w.cfg;
  const patIds33c = cfg.use33c ? state.patIds33c : null;
  const patIdsE   = cfg.useE   ? state.patIdsE   : null;
  const N_TACT = NPat.N_TACT_SLOTS;

  let tc = 0;
  for (let i = 0; i < n; i++) {
    const r = lr * (targetProbs[i] - probs[i]);
    if (r === 0) continue;
    if (patIds33c) {
      const idx = patIds33c[i];
      touched[tc++] = idx;
      delta[idx] += r;
    }
    if (patIdsE) {
      const idx = patIdsE[i];
      touched[tc++] = idx;
      delta[idx] += r;
    }
  }
  for (let i = 0; i < tc; i++) {
    const idx = touched[i];
    const d = delta[idx];
    if (d !== 0) {
      vals[idx] += d;
      delta[idx] = 0;
    }
  }
  if (cfg.useTactical !== false) {
    for (let k = 0; k < N_TACT; k++) {
      let acc = 0;
      for (let i = 0; i < n; i++) {
        acc += lr * (targetProbs[i] - probs[i]) * tact[i * N_TACT + k];
      }
      vals[tIds[k]] += acc;
    }
  }
  return tc + (cfg.useTactical !== false ? N_TACT : 0);
}

// Build current-player softmax target distribution from per-move V values.
function targetFromV(vValues, n, isBlack, T) {
  const logits = new Float64Array(n);
  const eps = 1e-7;
  for (let i = 0; i < n; i++) {
    const Vc = Math.max(eps, Math.min(1 - eps, vValues[i]));
    let logit = Math.log(Vc / (1 - Vc));
    if (!isBlack) logit = -logit;
    logits[i] = logit / T;
  }
  let maxL = -Infinity;
  for (let i = 0; i < n; i++) if (logits[i] > maxL) maxL = logits[i];
  let sum = 0;
  for (let i = 0; i < n; i++) { logits[i] = Math.exp(logits[i] - maxL); sum += logits[i]; }
  const inv = 1 / sum;
  for (let i = 0; i < n; i++) logits[i] *= inv;
  return logits;
}

// ── Combined move selection: npat-filter + vlibpat-search ────────────────────

const stateByN = new Map();

// Returns { move, npatChosenIndex } where npatChosenIndex is the index in
// state.moves of the move that was actually played (used as the npat target
// for cross-entropy update).  Returns null for the index if PASS is played
// (no npat update for PASS).
function filteredSearch(game) {
  let state = stateByN.get(game.N);
  if (!state) { state = NPat.createState(game.N); stateByN.set(game.N, state); }
  const game3 = game3FromGame2(game);
  // policyMove fills state.probs and state.moves and returns a sampled move
  // (we ignore the sampled move and use Bernoulli-on-probs ourselves).
  NPat.policyMove(game, state, npatWeights, Math, game3);
  const n = state.count;
  if (n === 0) return { move: PASS, npatChosenIndex: -1 };

  // Either full-width search (small fraction) or top-k by npat probability.
  const fullWidth = Math.random() < FULL_WIDTH_RATE;
  const included = new Uint8Array(n);
  let nIncluded = 0;
  if (fullWidth) {
    for (let i = 0; i < n; i++) included[i] = 1;
    nIncluded = n;
  } else {
    const k = Math.min(TOP_K, n);
    // Find top-k indices by descending probability.
    const idx = new Int32Array(n);
    for (let i = 0; i < n; i++) idx[i] = i;
    // Partial sort: simple full sort works fine for n ≤ ~100.
    const probs = state.probs;
    const sorted = Array.from(idx).sort((a, b) => probs[b] - probs[a]);
    for (let j = 0; j < k; j++) {
      included[sorted[j]] = 1;
      nIncluded++;
    }
  }

  // Evaluate vlibpat V over included candidates; pick argmax in current-player perspective.
  // On full-width steps, also collect all V values for the value-based npat update.
  const isBlack = game.current === BLACK;
  let bestI = -1;
  let bestVal = isBlack ? -Infinity : Infinity;
  const vValues = fullWidth ? new Float64Array(n) : null;
  for (let i = 0; i < n; i++) {
    if (!included[i]) continue;
    const features = extractFeatures(game, vlibpatPrep, true, state.moves[i]);
    evaluateFeatures(features, vlibpatW);
    if (vValues) vValues[i] = features.val;
    if (isBlack) {
      if (features.val > bestVal) { bestVal = features.val; bestI = i; }
    } else {
      if (features.val < bestVal) { bestVal = features.val; bestI = i; }
    }
  }

  return { move: state.moves[bestI], npatChosenIndex: bestI, candidates: nIncluded, fullWidth, vValues, isBlack };
}

// ── Training game ────────────────────────────────────────────────────────────

function trainGame(N) {
  const game = new Game2(N, false);
  const game3 = new Game3(N);
  const maxMoves = N * N * 4;
  const tStart = Date.now();

  let prev2 = null, prev1 = null;
  let moves = 0, candidatesAcc = 0, candidatesN = 0;
  let npatUpdates = 0;
  // Snapshot of npat state per step (so we can apply the cross-entropy update
  // after the game; keeping the inline approach also works but doing it after
  // the move is clean — state.probs is overwritten on the next call to
  // policyMove for this state).  We update inline.
  while (!game.gameOver && moves < maxMoves) {
    // Compute V of current state (for vlibpat TD).
    const features = extractFeatures(game, vlibpatPrep);
    evaluateFeatures(features, vlibpatW);
    if (prev2 !== null) tdUpdate(prev2, features.val, VLIBPAT_LR);
    prev2 = prev1; prev1 = features;

    let mv;
    if (Math.random() < EPSILON) {
      // Random legal move; no training updates this step.
      // Reuse npat's state.moves to enumerate non-eye legal moves.
      let state = stateByN.get(N);
      if (!state) { state = NPat.createState(N); stateByN.set(N, state); }
      NPat.policyMove(game, state, npatWeights, Math, game3);
      mv = state.count === 0 ? PASS : state.moves[Math.floor(Math.random() * state.count)];
    } else {
      const r = filteredSearch(game);
      mv = r.move;
      candidatesAcc += r.candidates || 0;
      candidatesN++;
      if (r.npatChosenIndex >= 0 && r.fullWidth) {
        // Value-based soft-target update only on full-width steps.
        const state = stateByN.get(N);  // same state used by filteredSearch
        const target = targetFromV(r.vValues, state.count, r.isBlack, TEMPERATURE);
        npatTotalUpdates += softTargetUpdate(state, target, npatWeights, NPAT_LR) || 0;
        npatUpdates++;
      }
    }
    game.play(mv);
    game3.play(mv);
    moves++;
  }

  // Terminal outcome → final 2 TD updates.
  const outcome = absoluteOutcome(game);
  for (const f of [prev2, prev1]) {
    if (f === null) continue;
    tdUpdate(f, outcome, VLIBPAT_LR);
  }

  return {
    elapsedMs: Date.now() - tStart,
    moves,
    candidatesAvg: candidatesN > 0 ? candidatesAcc / candidatesN : 0,
    npatUpdates,
  };
}

// ── Header / log ─────────────────────────────────────────────────────────────

console.log(`vlibpat: lr=${VLIBPAT_LR}  ema-alpha=${EMA_ALPHA}  specs=${JSON.stringify(vlibpatSpecs)}`);
console.log(`npat:    lr=${NPAT_LR}     ema-alpha=${NPAT_EMA_ALPHA}  3x3c+tactical`);
console.log(`epsilon=${EPSILON}  top-k=${TOP_K}  full-width-rate=${FULL_WIDTH_RATE}  temperature=${TEMPERATURE}  train-size=${TRAIN_SIZE}`);
console.log(`Out: vlibpat → ${VLIBPAT_SAVE}`);
console.log(`     npat    → ${NPAT_SAVE}`);
console.log();
console.log([
  'game'.padStart(6),
  'elapsedS'.padStart(8),
  'tGameMs'.padStart(8),
  'vWts'.padStart(8),
  'nWts'.padStart(7),
  'avglen'.padStart(7),
  'cands'.padStart(6),
  'avgVw'.padStart(7),
  'avgNw'.padStart(7),
].join('  '));

// ── Main loop ────────────────────────────────────────────────────────────────

const t0 = Date.now();
let g = 0;

let movesAcc = 0, candAcc = 0, candN = 0;
let elapsedMsAcc = 0;
let lastPrintG = 0;
let limitReached = false;

while (true) {
  g++;
  const r = trainGame(TRAIN_SIZE);
  movesAcc += r.moves;
  candAcc += r.candidatesAvg * (r.candidatesAvg > 0 ? 1 : 0);
  if (r.candidatesAvg > 0) candN++;
  elapsedMsAcc += r.elapsedMs;
  applyVlibpatEMA(EMA_ALPHA);
  NPat.applyEMA(npatWeights, NPAT_EMA_ALPHA);

  if (LIMIT_GAMES > 0 && g >= LIMIT_GAMES) limitReached = true;

  if (g % PRINT_EVERY === 0 || limitReached) {
    // vlibpat avg|w|
    let vAbsSum = 0;
    for (const v of vlibpatW.values()) vAbsSum += Math.abs(v);
    const vAvg = vlibpatW.size > 0 ? vAbsSum / vlibpatW.size : 0;
    // npat avg|w| over non-zero
    let nAbsSum = 0, nNonZero = 0;
    const nVals = npatWeights.vals;
    const nN    = npatWeights.size;
    for (let i = 0; i < nN; i++) {
      const a = Math.abs(nVals[i]);
      if (a === 0) continue;
      nNonZero++;
      nAbsSum += a;
    }
    const nAvg = nNonZero > 0 ? nAbsSum / nNonZero : 0;

    const cycleN = g - lastPrintG;
    const cycleAvgGameMs = cycleN > 0 ? elapsedMsAcc / cycleN : 0;
    const elapsedS = Math.floor((Date.now() - t0) / 1000);
    const avgLen = cycleN > 0 ? movesAcc / cycleN : 0;
    const avgCands = candN > 0 ? candAcc / candN : 0;

    console.log([
      `${g}`.padStart(6),
      `${elapsedS}`.padStart(8),
      `${cycleAvgGameMs.toFixed(1)}`.padStart(8),
      `${vlibpatW.size}`.padStart(8),
      `${nNonZero}`.padStart(7),
      `${avgLen.toFixed(1)}`.padStart(7),
      `${avgCands.toFixed(1)}`.padStart(6),
      `${vAvg.toFixed(4)}`.padStart(7),
      `${nAvg.toFixed(4)}`.padStart(7),
    ].join('  '));

    saveVlibpat(VLIBPAT_SAVE);
    saveNpat(NPAT_SAVE);

    movesAcc = 0; candAcc = 0; candN = 0; elapsedMsAcc = 0;
    lastPrintG = g;

    if (limitReached) break;
  }
}

if (LIMIT_GAMES > 0) {
  console.log(`Reached --limit ${LIMIT_GAMES} games — saved ${VLIBPAT_SAVE} and ${NPAT_SAVE}`);
}
