#!/usr/bin/env node
'use strict';

// train-npat.js — REINFORCE-style policy iterator over nine-pattern features.
//
// Each candidate move is represented by 9 canonical 3×3 pattern IDs (the nine
// windows that overlap the move — see npat-lib.js).  A linear logit policy
//   π(a|s) = softmax( Σ_{p ∈ f_a} w[p] )
// is trained by REINFORCE on the game's terminal outcome.
//
// Per-step update (for the mover at step t):
//   Δw[p] = lr · A_t · ( count(p, f_{a_t}) − Σ_i π(i|s_t) · count(p, f_i) )
// where A_t = R_t − b   (R_t ∈ {−1, 0, +1} from mover's perspective, b is an
// exponential-moving-average baseline to reduce variance).
//
// Weights are stored sparsely in a Map<pid, weight>.  They are saved at every
// progress print (interval grows geometrically).  Ctrl-C to stop.
//
// Usage:
//   node train-npat.js [--size 9] [--lr 0.05] [--baseline 0.95]
//                      [--load path] [--save path] [--eval-agent random]

const path = require('path');
const fs   = require('fs');

const { Game2, BLACK, PASS } = require('./game2.js');
const { Game3 } = require('./game3.js');
const NPat = require('./npat-lib.js');
const Util = require('./util.js');

// ── Arguments ─────────────────────────────────────────────────────────────────

const opts       = Util.parseArgs(process.argv.slice(2),
  ['help', 'use-3x3c', 'use-A', 'use-B', 'use-G']);
const TRAIN_SIZE = parseInt(opts['train-size'] || opts.size || '9', 10);
const EVAL_SIZE  = parseInt(opts['eval-size']  || opts.size || opts['train-size'] || '9', 10);
const LR         = parseFloat(opts.lr || '0.05');
const BASELINE   = parseFloat(opts.baseline || '0.95');   // EMA decay for reward baseline; 0 disables
const EPSILON    = Math.min(parseFloat(opts.epsilon || '0.0'), 0.9999);
const BETA       = parseFloat(opts.beta || '0.0');          // entropy-bonus coefficient; 0 disables
const USE_33C    = !!opts['use-3x3c'];                        // enable centered 3×3 window
const USE_A      = !!opts['use-A'];                           // enable Type A window
const USE_B      = !!opts['use-B'];                           // enable Type B window
const USE_G      = !!opts['use-G'];                           // enable grown-pattern window
const EVAL_AGENT = opts.eval || opts['eval-agent'] || 'random';
const SAVE_PATH  = opts.save || `out/npat-${Math.random().toString(36).slice(2, 10)}.js`;
const LOAD_PATH  = opts.load || null;

// ── Weights ───────────────────────────────────────────────────────────────────

let weights = NPat.createWeights({ use33c: USE_33C, useA: USE_A, useB: USE_B, useG: USE_G });
let ema     = 0;                     // EMA of terminal outcome from mover's perspective

// ── Persistence ───────────────────────────────────────────────────────────────

function saveWeights(filePath, w, meta) {
  const parts = [];
  for (const [rawId, denseIdx] of w.map) {
    // JSON.stringify handles both number and string raw ids; string ids come
    // from shape types with hashed canonicalisation (e.g., the grown pattern).
    parts.push(`[${JSON.stringify(rawId)},${+w.vals[denseIdx].toFixed(6)}]`);
  }
  const list = '[' + parts.join(',') + ']';
  const src = [
    "'use strict';",
    '// Auto-generated by train-npat.js — do not edit by hand.',
    `const npatModel = {`,
    `  ema: ${+meta.ema.toFixed(6)},`,
    `  weights: new Map(${list}),`,
    `};`,
    "if (typeof module !== 'undefined') module.exports = npatModel;",
    "else window.npatModel = npatModel;",
  ].join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, src);
}

function loadWeights(filePath) {
  delete require.cache[require.resolve(path.resolve(filePath))];
  const raw = require(path.resolve(filePath));
  const w = NPat.createWeights({
    initialCapacity: Math.max(1024, raw.weights.size | 0),
    use33c: USE_33C, useA: USE_A, useB: USE_B, useG: USE_G,
  });
  for (const [rawId, val] of raw.weights) {
    const idx = NPat.internWeight(w, rawId);
    w.vals[idx] = val;
  }
  return { weights: w, ema: raw.ema ?? 0 };
}

// ── Training ──────────────────────────────────────────────────────────────────

// Play one self-play game and apply REINFORCE updates after it ends.
// Returns game-level stats for logging.
function trainGame(N) {
  const game  = new Game2(N, false);
  const game3 = new Game3(N);  // kept in lockstep for ladder analysis
  const maxMoves = N * N * 4;
  const tStart   = Date.now();

  // Per-step record: enough to replay the gradient with the known outcome.
  // We store (player, chosenIndex, per-shape patIds, tact, probs, count).
  // To minimise allocations we use per-step state snapshots.
  const steps = [];
  const state = NPat.createState(N);

  let moves = 0;
  while (!game.gameOver && moves < maxMoves) {
    const player = game.current;
    let choice;

    if (EPSILON > 0 && Math.random() < EPSILON) {
      // Uniform exploration over legal non-eye moves.  Still need features
      // (and π) for the gradient, so run the same extraction path.
      const mv = NPat.policyMove(game, state, weights, Math, game3);
      if (state.count === 0) { choice = { move: PASS, index: -1, prob: 1 }; }
      else {
        const i = Math.floor(Math.random() * state.count);
        choice = { move: state.moves[i], index: i, prob: state.probs[i] };
      }
    } else {
      choice = NPat.policyMove(game, state, weights, Math, game3);
    }

    if (choice.index >= 0) {
      // Snapshot features + distribution (copy just the slice we need).
      // We reuse state.touched across snapshots as the REINFORCE scratch
      // buffer — reinforceUpdate zeros each touched slot after applying.
      const n = state.count;
      const patIds33c = new Int32Array(n);
      patIds33c.set(state.patIds33c.subarray(0, n));
      const patIdsA = new Int32Array(n);
      patIdsA.set(state.patIdsA.subarray(0, n));
      const patIdsB = new Int32Array(n);
      patIdsB.set(state.patIdsB.subarray(0, n));
      const patIdsG = new Int32Array(n);
      patIdsG.set(state.patIdsG.subarray(0, n));
      const tact = new Uint8Array(n * NPat.N_TACT_SLOTS);
      tact.set(state.tact.subarray(0, n * NPat.N_TACT_SLOTS));
      const probs = new Float64Array(n);
      probs.set(state.probs.subarray(0, n));
      steps.push({ player, chosenIndex: choice.index, count: n, patIds33c, patIdsA, patIdsB, patIdsG, tact, probs, touched: state.touched });
    }

    game.play(choice.move);
    game3.play(choice.move);
    moves++;
  }

  // Terminal outcome: +1 if BLACK wins else -1 (use calcWinner; ties → 0).
  const winner = game.calcWinner();
  const outcomeBlack = winner === BLACK ? 1 : (winner === 0 ? 0 : -1);

  // REINFORCE: apply Δw per step with advantage = R − baseline, where R is from
  // the MOVER'S perspective.
  let stepsApplied = 0;
  let weightUpdates = 0;
  for (const s of steps) {
    const R = s.player === BLACK ? outcomeBlack : -outcomeBlack;
    const adv = BASELINE > 0 ? (R - ema) : R;
    weightUpdates += NPat.reinforceUpdate(s, s.chosenIndex, adv, weights, LR) || 0;
    if (BETA > 0) NPat.entropyBonusUpdate(s, weights, LR * BETA);
    stepsApplied++;
  }

  if (BASELINE > 0 && steps.length > 0) {
    // Update EMA towards the black-perspective outcome (so it's consistent).
    // Note: we subtract ema from mover-perspective R in the step update, which
    // is a small approximation — the baseline is still unbiased only if it is
    // independent of mover.  In practice the asymmetry washes out quickly.
    ema = BASELINE * ema + (1 - BASELINE) * outcomeBlack;
  }

  return {
    elapsedMs: Date.now() - tStart,
    moves,
    stepsApplied,
    weightUpdates,
    outcomeBlack,
  };
}

// ── Evaluation against a reference agent ─────────────────────────────────────

function evalVsReference(N, refGetMove, nGames) {
  const state = NPat.createState(N);
  const results = [];
  for (let g = 0; g < nGames; g++) {
    const policyIsBlack = (g % 2 === 0);
    const game  = new Game2(N, false);
    const game3 = new Game3(N);  // lockstep copy for ladder analysis
    const maxMoves = N * N * 4;
    let m = 0;
    while (!game.gameOver && m++ < maxMoves) {
      let idx;
      if ((game.current === BLACK) === policyIsBlack) {
        idx = NPat.greedyMove(game, state, weights, game3);
      } else {
        const mv = refGetMove(game);
        idx = mv && mv.move !== undefined ? mv.move : PASS;
      }
      game.play(idx);
      game3.play(idx);
    }
    const winner = game.calcWinner();
    results.push((winner === BLACK) === policyIsBlack ? 1 : 0);
  }
  return results;
}

// ── CLI setup ─────────────────────────────────────────────────────────────────

if (opts.help) {
  console.log(`Usage: node train-npat.js [options]
  --size N         | --train-size N | --eval-size N   (default 9)
  --lr F           learning rate (default 0.05)
  --baseline F     EMA decay for reward baseline (default 0.95; 0 disables)
  --epsilon F      uniform-random exploration rate (default 0)
  --beta F         entropy-bonus coefficient (default 0; applied on top of lr)
  --use-3x3c       enable the centered 3×3 shape window (default off)
  --use-A          enable the Type A shape window       (default off)
  --use-B          enable the Type B shape window       (default off)
  --use-G          enable the grown-pattern shape window (default off)
  --eval-agent S   reference agent in ai/ (default random)
  --load PATH      resume from saved weights
  --save PATH      where to save (default out/npat-<rand>.js)
`);
  process.exit(0);
}

const { getMove: evalGetMove } =
  require(path.join(__dirname, 'ai', EVAL_AGENT + '.js'));

if (LOAD_PATH) {
  if (fs.existsSync(LOAD_PATH)) {
    const loaded = loadWeights(LOAD_PATH);
    weights = loaded.weights;
    ema     = loaded.ema;
    console.log(`Loaded ${weights.size} weights from ${LOAD_PATH}  (ema=${ema.toFixed(3)})`);
  } else {
    console.warn(`Warning: --load file not found: ${LOAD_PATH}`);
  }
}

console.log(`lr=${LR}  baseline=${BASELINE}  epsilon=${EPSILON}  beta=${BETA}`);
console.log(`features: tactical=ALWAYS  3x3c=${USE_33C ? 'ON' : 'off'}  A=${USE_A ? 'ON' : 'off'}  B=${USE_B ? 'ON' : 'off'}  G=${USE_G ? `ON(patStones=${NPat.PAT_STONES},max=${NPat.MAX_PAT_SIZE})` : 'off'}`);
console.log(`train-size=${TRAIN_SIZE}  eval-size=${EVAL_SIZE}  ref=${EVAL_AGENT}`);
console.log(`Out: ${SAVE_PATH}${LOAD_PATH ? `  (resumed from ${LOAD_PATH})` : ''}`);
console.log();

console.log([
  'games'  .padStart(7),
  'weights'.padStart(9),
  'avg|w|' .padStart(7),
  'upd/pat'.padStart(7),
].join('  '));

// ── Main loop ─────────────────────────────────────────────────────────────────

const t0 = Date.now();
let nextPrintAt = t0 + 1000;
let g = 0;
let totalUpdates = 0;

while (true) {
  g++;
  const { weightUpdates } = trainGame(TRAIN_SIZE);
  totalUpdates += weightUpdates;

  if (Date.now() >= nextPrintAt) {
    // Count only interned pids that have received a non-zero gradient: pids
    // are interned on first sight in extractFeatures, so weights.size counts
    // every pattern ever seen — the "learned" count is the non-zero subset.
    let wAbsSum = 0, wNonZero = 0;
    const vals = weights.vals;
    const wN   = weights.size;
    for (let i = 0; i < wN; i++) {
      const a = Math.abs(vals[i]);
      if (a === 0) continue;
      wNonZero++;
      wAbsSum += a;
    }
    const wAvg    = wNonZero > 0 ? wAbsSum / wNonZero : 0;
    const updPerPat = wNonZero > 0 ? totalUpdates / wNonZero : 0;

    const nextMs = Date.now() - t0;

    console.log([
      String(g)                .padStart(7),
      String(wNonZero)         .padStart(9),
      wAvg.toFixed(3)          .padStart(7),
      updPerPat.toFixed(1)     .padStart(7),
    ].join('  '));

    saveWeights(SAVE_PATH, weights, { ema });
    nextPrintAt = t0 + Math.round(nextMs * 1.4);
  }
}
