'use strict';

// BROWSER-COMPATIBLE: no Node.js-only APIs (require, process, etc.).
// Wrapped in an IIFE to avoid polluting the global namespace.
// Loaded as a plain <script> tag; do not add require/module/process at top level.

(function () {

const _isNode = typeof process !== 'undefined' && process.versions && process.versions.node;

const performance = (typeof window !== 'undefined') ? window.performance
  : require('perf_hooks').performance;

const { PASS, BLACK, WHITE } = _isNode ? require('../game2.js') : window.Game2;
const Util = _isNode ? require('../util.js') : window.Util;
const path = _isNode ? require('path') : null;

const { createState, extractFeatures } = _isNode ? require('../ppat.js') : window.PPatterns;

// Load trained weights if available (generated by train-ppat.js).
// Set PPAT_WEIGHTS env var (Node) or window.PPATWeights (browser) to provide them.
let _weights = null;
if (_isNode) {
  const weightsPath = Util.envStr('PPAT_WEIGHTS', '');
  if (weightsPath) try { _weights = require(path.resolve(weightsPath)); } catch (e) { console.warn('rave-ppat: could not load weights:', e.message); }
} else {
  _weights = (typeof window !== 'undefined' && window.PPATWeights) || null;
}

// Module-level ppat buffers — reused across all playouts.
let _ppatState = null;
let _logits    = new Float32Array(512);
let _probs     = new Float32Array(512);

function _ensurePpatState(N) {
  if (_ppatState === null || _ppatState.moves.length < N * N)
    _ppatState = createState(N);
}

function getMove(game, timeBudgetMs) {
  if (game.gameOver) return { type: 'pass', move: PASS, info: 'game already over' };

  const game2      = game.cells ? game.clone() : game.toGame2();
  const N = game2.N;
  _ensurePpatState(N);
  const patW  = _weights ? _weights.pat  : null;
  const prevW = _weights ? _weights.prev : null;
  extractFeatures(game2, _ppatState);
  const n = _ppatState.count;
  if (n === 0) {
    return PASS;
  }

  if (_logits.length < n) { _logits = new Float32Array(n * 2); _probs = new Float32Array(n * 2); }
  for (let i = 0; i < n; i++) {
    let v = patW[_ppatState.patIds[i]];
    let m = _ppatState.prevMasks[i];
    for (let b = 0; m; b++, m >>= 1) if (m & 1) v += prevW[b];
    _logits[i] = v;
  }
  let max = _logits[0];
  for (let i = 1; i < n; i++) if (_logits[i] > max) max = _logits[i];
  let sum = 0;
  for (let i = 0; i < n; i++) { _probs[i] = Math.exp(_logits[i] - max); sum += _probs[i]; }
  const inv = 1 / sum;
  for (let i = 0; i < n; i++) _probs[i] *= inv;
  let r = Math.random(), chosen = n - 1;
  for (let i = 0; i < n; i++) { r -= _probs[i]; if (r <= 0) { chosen = i; break; } }
  const m = _ppatState.moves[chosen];
  const result = m === PASS ? { type: 'pass', move: PASS }
                            : { type: 'place', move: m, x: m % N, y: (m / N) | 0 };
  return result;
}

if (typeof module !== 'undefined') module.exports = { getMove };
else window.getMove = getMove;

})();
