'use strict';

// BROWSER-COMPATIBLE: no Node.js-only APIs (require, process, etc.).
// Wrapped in an IIFE to avoid polluting the global namespace.
// Loaded as a plain <script> tag; do not add require/module/process at top level.

(function () {

const _isNode = typeof process !== 'undefined' && process.versions && process.versions.node;

const performance = (typeof window !== 'undefined') ? window.performance
  : require('perf_hooks').performance;

const { PASS, BLACK, WHITE } = _isNode ? require('../game2.js') : window.Game2;
const Util = _isNode ? require('../util.js') : window.Util;
const path = _isNode ? require('path') : null;

const { createState, ppatMove } = _isNode ? require('../ppat-lib.js') : window.PPatterns;

// Load trained weights if available (generated by train-ppat.js).
// Set PPAT_WEIGHTS env var (Node) or window.PPATWeights (browser) to provide them.
let _weights = null;
if (_isNode) {
  const weightsPath = Util.envStr('PPAT_WEIGHTS', '');
  if (weightsPath) try { _weights = require(path.resolve(weightsPath)); } catch (e) { console.warn('ppat: could not load weights:', e.message); }
} else {
  _weights = (typeof window !== 'undefined' && window.PPATWeights) || null;
}

let _ppatState = null;
function _ensureState(N) {
  if (_ppatState === null || _ppatState.moves.length < N * N)
    _ppatState = createState(N);
}

function getMove(game, timeBudgetMs) {
  if (game.gameOver) return { type: 'pass', move: PASS, info: 'game already over' };

  const game2 = game.cells ? game.clone() : game.toGame2();
  const N = game2.N;
  _ensureState(N);
  const m = ppatMove(game2, _ppatState, _weights);
  const result = m === PASS ? { type: 'pass', move: PASS }
                            : { type: 'place', move: m, x: m % N, y: (m / N) | 0 };
  return result;
}

if (typeof module !== 'undefined') module.exports = { getMove };
else window.getMove = getMove;

})();
